ci: Check integration test coverage

diff --git a/.ci/integration.cloudbuild.yaml b/.ci/integration.cloudbuild.yaml
--- a/.ci/integration.cloudbuild.yaml
+++ b/.ci/integration.cloudbuild.yaml
@@ -43,7 +43,7 @@ steps:
     args:
       - -c
       - |
-        go test -race -v -tags=integration,cloudsqlpg ./tests
+        go test -race -cover -v -coverprofile=cloud_sql_pg_coverage.out -tags=integration,cloudsqlpg ./tests ./internal/sources/cloudsqlpg
 
   - id: "alloydb-pg"
     name: golang:1
@@ -64,7 +64,7 @@ steps:
     args:
       - -c
       - |
-        go test -race -v -tags=integration,alloydb ./tests
+        go test -race -cover -coverprofile=alloydb_pg_coverage.out -v -tags=integration,alloydb ./tests ./internal/sources/alloydbpg ./internal/tools/postgressql
 
   - id: "postgres"
     name: golang:1
@@ -83,7 +83,7 @@ steps:
     args:
       - -c
       - |
-        go test -race -v -tags=integration,postgres ./tests
+        go test -race -cover -coverprofile=postgres_coverage.out -v -tags=integration,postgres ./tests ./internal/sources/postgres ./internal/tools/postgressql
 
   - id: "spanner"
     name: golang:1
@@ -100,7 +100,7 @@ steps:
     args:
       - -c
       - |
-        go test -race -v -tags=integration,spanner ./tests
+        go test -race -cover -coverprofile=spanner_coverage.out -v -tags=integration,spanner ./tests ./internal/sources/spanner ./internal/tools/spanner
 
   - id: "neo4j"
     name: golang:1
@@ -117,7 +117,7 @@ steps:
     args:
       - -c
       - |
-        go test -race -v -tags=integration,neo4j ./tests
+        go test -race -cover -coverprofile=neo4j_coverage.out -v -tags=integration,neo4j ./tests ./internal/sources/spanner ./internal/tools/spanner
 
   - id: "cloud-sql-mssql"
     name: golang:1
@@ -138,7 +138,7 @@ steps:
     args:
       - -c
       - |
-        go test -race -v -tags=integration,cloudsqlmssql ./tests
+        go test -race -cover -coverprofile=cloud_sql_mssql_coverage.out -v -tags=integration,cloudsqlmssql ./tests ./internal/sources/cloudsqlmssql ./internal/tools/mssqlsql
 
   - id: "cloud-sql-mysql"
     name: golang:1
@@ -151,15 +151,14 @@ steps:
       - "CLOUD_SQL_MYSQL_DATABASE=$_DATABASE_NAME"
       - "CLOUD_SQL_MYSQL_REGION=$_REGION"
       - "SERVICE_ACCOUNT_EMAIL=$SERVICE_ACCOUNT_EMAIL"
-    secretEnv:
-      ["CLOUD_SQL_MYSQL_USER", "CLOUD_SQL_MYSQL_PASS", "CLIENT_ID"]
+    secretEnv: ["CLOUD_SQL_MYSQL_USER", "CLOUD_SQL_MYSQL_PASS", "CLIENT_ID"]
     volumes:
       - name: "go"
         path: "/gopath"
     args:
       - -c
       - |
-        go test -race -v -tags=integration,cloudsqlmysql ./tests
+        go test -race -cover -coverprofile=cloud_sql_mysql_coverage.out -v -tags=integration,cloudsqlmysql ./tests ./internal/sources/cloudsqlmysql ./internal/tools/mysqlsql
 
   - id: "mysql"
     name: golang:1
@@ -178,7 +177,7 @@ steps:
     args:
       - -c
       - |
-        go test -race -v -tags=integration,mysql ./tests
+        go test -race -cover -coverprofile=mysql_coverage.out -v -tags=integration,mysql ./tests ./internal/sources/mysql ./internal/tools/mysqlsql
 
   - id: "mssql"
     name: golang:1
@@ -197,7 +196,7 @@ steps:
     args:
       - -c
       - |
-        go test -race -v -tags=integration,mssql ./tests
+        go test -race -cover -coverprofile=mssql_coverage.out -v -tags=integration,mssql ./tests ./internal/sources/mssql ./internal/tools/mssqlsql
 
   - id: "dgraph"
     name: golang:1
@@ -212,7 +211,20 @@ steps:
     args:
       - -c
       - |
-        go test -race -v -tags=integration,dgraph ./tests
+        go test -race -cover -coverprofile=dgraph_coverage.out -v -tags=integration,dgraph ./tests ./internal/sources/dgraph ./internal/tools/dgraph
+
+  - id: "check-coverage"
+    name: golang:1
+    entrypoint: /bin/bash
+    script: |
+      set -e
+      for file in $(find . -name "*_coverage.out"); do
+        coverage=$(go tool cover -func="$file" | grep "total:" | awk '{print $3}' | sed 's/%//');
+        echo "Coverage for $file: $coverage%";
+        if [[ "$coverage" -lt 90 ]]; then
+          echo "Error: Coverage below 90% in $file";
+          exit 1;
+        fi
 
 availableSecrets:
   secretManager:
@@ -247,10 +259,9 @@ availableSecrets:
     - versionName: projects/$PROJECT_ID/secrets/mysql_pass/versions/latest
       env: MYSQL_PASS
     - versionName: projects/$PROJECT_ID/secrets/mssql_user/versions/latest
-      env: MSSQL_USER 
+      env: MSSQL_USER
     - versionName: projects/$PROJECT_ID/secrets/mssql_pass/versions/latest
       env: MSSQL_PASS
-
 
 options:
   logging: CLOUD_LOGGING_ONLY
